"use client"
import Link from "next/link"
import { ChangeEvent,useEffect,useRef,useState } from "react"
import { Camera,Save } from "lucide-react"
import { DESO_IDENTITY_ORIGIN,restoreIdentitySession,type ViaIdentitySession } from "../../deso-identity-session"
type Profile={username:string;description:string;profilePic:string|null;creatorBasisPoints:number|null;stakeMultipleBasisPoints:number|null;isHidden:boolean}
export default function EditProfilePage(){
 const [session,setSession]=useState<ViaIdentitySession|null>(null),[ready,setReady]=useState(false),[username,setUsername]=useState(""),[description,setDescription]=useState(""),[profilePic,setProfilePic]=useState(""),[fr,setFr]=useState("0"),[stakeMultiple,setStakeMultiple]=useState<number|null>(null),[isHidden,setIsHidden]=useState<boolean|null>(null),[message,setMessage]=useState("")
 const popup=useRef<Window|null>(null)
 useEffect(()=>{const s=restoreIdentitySession();setSession(s);if(!s)return;fetch("/api/via/profile?identity="+encodeURIComponent(s.publicKey),{cache:"no-store"}).then(r=>r.json()).then(d=>{if(!d?.profile)return;setUsername(d.profile.username||"");setDescription(d.profile.description||"");setProfilePic(d.profile.profilePic||"");setFr(String(d.profile.creatorBasisPoints??0));setStakeMultiple(typeof d.profile.stakeMultipleBasisPoints==="number"?d.profile.stakeMultipleBasisPoints:null);setIsHidden(typeof d.profile.isHidden==="boolean"?d.profile.isHidden:null);setReady(true)})},[])
 useEffect(()=>{const fn=async(e:MessageEvent)=>{if(e.origin!==DESO_IDENTITY_ORIGIN||e.source!==popup.current)return;const signed=e.data?.payload?.signedTransactionHex;if(typeof signed!=="string"||!signed)return;popup.current?.close();popup.current=null;setMessage("Saving approved profile on DeSo…");const r=await fetch("/api/via/profile/update",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"submit",signedTransactionHex:signed})});setMessage(r.ok?"Profile update submitted to DeSo.":"Profile update could not be submitted.")};window.addEventListener("message",fn);return()=>window.removeEventListener("message",fn)},[])
 function choosePhoto(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file||file.size>2_000_000){setMessage("Choose an image up to 2 MB.");return}const reader=new FileReader();reader.onload=()=>setProfilePic(typeof reader.result==="string"?reader.result:"");reader.readAsDataURL(file)}
 async function save(){if(!session||stakeMultiple===null||isHidden===null){setMessage("Current DeSo profile settings are not available; nothing was changed.");return;}setMessage("Preparing DeSo profile update…");const r=await fetch("/api/via/profile/update",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"prepare",publicKey:session.publicKey,username,description,profilePic,creatorBasisPoints:Number(fr),stakeMultipleBasisPoints:stakeMultiple,isHidden})});const d=await r.json();if(!r.ok||!d.transactionHex){setMessage("Profile update could not be prepared.");return}const w=window.open(DESO_IDENTITY_ORIGIN+"/approve?tx="+encodeURIComponent(d.transactionHex),"via-profile-approve","popup=yes,width=800,height=900");if(!w){setMessage("DeSo approval window was blocked.");return}popup.current=w;setMessage("Review and approve the change in DeSo Identity.")}
 if(!session)return <main className="min-h-screen bg-[#050807] p-5 text-zinc-100"><p>Log in with DeSo Identity to edit your profile.</p><Link href="/profile">Back</Link></main>
 return <main className="min-h-screen bg-[#050807] p-4 text-zinc-100"><section className="mx-auto max-w-xl rounded-2xl border border-[#8fd4a9]/25 bg-[#0b1710] p-4">
 <div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.16em] text-[#8fd4a9]">VIA · DeSo</p><h1 className="text-xl font-semibold">Edit Profile</h1></div><Link href="/profile" className="text-sm text-zinc-400">Cancel</Link></div>
 <div className="mt-5 flex justify-center"><label className="relative cursor-pointer"><div className="h-24 w-24 overflow-hidden rounded-full border border-[#8fd4a9]/35 bg-black/30">{profilePic?<img src={profilePic} alt="" className="h-full w-full object-cover"/>:<span className="grid h-full place-items-center text-3xl">V</span>}</div><span className="absolute bottom-0 right-0 grid h-9 w-9 place-items-center rounded-full bg-[#10271a] text-[#9adbb2]"><Camera className="h-4 w-4"/></span><input className="hidden" type="file" accept="image/*" onChange={choosePhoto}/></label></div>
 <div className="mt-5 grid gap-4"><label className="grid gap-1 text-sm">USERNAME<input value={username} maxLength={25} onChange={e=>setUsername(e.target.value)} className="rounded-xl border border-zinc-700 bg-[#050807] p-3"/></label><label className="grid gap-1 text-sm">DESCRIPTION<textarea value={description} maxLength={20000} rows={6} onChange={e=>setDescription(e.target.value)} className="rounded-xl border border-zinc-700 bg-[#050807] p-3"/></label><label className="grid gap-1 text-sm">FOUNDER REWARD PERCENTAGE<input type="number" min="0" max="100" step=".01" value={(Number(fr)/100).toString()} onChange={e=>setFr(String(Math.round(Number(e.target.value)*100)))} className="rounded-xl border border-zinc-700 bg-[#050807] p-3"/></label></div>
 <button onClick={()=>void save()} disabled={!ready||!username.trim()} className="mt-5 flex min-h-11 w-full items-center justify-center gap-2 rounded-xl border border-[#8fd4a9]/45 bg-[#10271a] font-semibold text-[#9adbb2] disabled:opacity-40"><Save className="h-4 w-4"/>Save with DeSo Identity</button><p role="status" className="mt-3 text-sm text-zinc-400">{message||"Changes require your DeSo Identity approval."}</p>
 </section></main>
}