"use client"
import { useEffect, useRef, useState } from "react"
import { DESO_IDENTITY_ORIGIN, restoreIdentitySession, VIA_IDENTITY_EVENT, type ViaIdentitySession } from "./deso-identity-session"
type Edition={serialNumber:number;isPending:boolean;ownerPublicKey?:string}
export default function NFTAcceptTransferControl({postHash,editions}:{postHash:string;editions:Edition[]}){
 const [session,setSession]=useState<ViaIdentitySession|null>(null); const [confirmed,setConfirmed]=useState(false); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const popupRef=useRef<Window|null>(null)
 const pending=editions.filter(e=>session&&e.isPending&&e.ownerPublicKey===session.publicKey)
 useEffect(()=>{setSession(restoreIdentitySession());const f=(e:Event)=>setSession((e as CustomEvent<ViaIdentitySession|null>).detail??restoreIdentitySession());window.addEventListener(VIA_IDENTITY_EVENT,f);return()=>window.removeEventListener(VIA_IDENTITY_EVENT,f)},[])
 useEffect(()=>{const f=async(event:MessageEvent)=>{if(event.origin!==DESO_IDENTITY_ORIGIN||event.source!==popupRef.current||!event.data||typeof event.data!=="object")return;const d=event.data as Record<string,unknown>;const p=d.payload;if(d.service!=="identity"||!p||typeof p!=="object"||Array.isArray(p))return;const signed=(p as Record<string,unknown>).signedTransactionHex;if(typeof signed!=="string"||!signed)return;popupRef.current?.close();popupRef.current=null;setBusy(true);setMessage("Submitting accepted transfer to DeSo…");try{const r=await fetch("/api/via/nft/accept-transfer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"submit",signedTransactionHex:signed})});const x=await r.json() as {ok?:boolean};if(!r.ok||!x.ok)throw new Error();setMessage("NFT transfer accepted on DeSo.");setConfirmed(false)}catch{setMessage("Transfer acceptance could not be submitted. VIA changed nothing.")}finally{setBusy(false)}};window.addEventListener("message",f);return()=>{window.removeEventListener("message",f);popupRef.current?.close();popupRef.current=null}},[])
 async function accept(serialNumber:number){if(!session||!confirmed||busy)return;setBusy(true);setMessage("Preparing transfer acceptance…");try{const r=await fetch("/api/via/nft/accept-transfer",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"prepare",publicKey:session.publicKey,postHash,serialNumber})});const x=await r.json() as {ok?:boolean;transactionHex?:string};if(!r.ok||!x.ok||!x.transactionHex)throw new Error();const popup=window.open(DESO_IDENTITY_ORIGIN+"/approve?tx="+encodeURIComponent(x.transactionHex),"via-accept-nft-transfer","popup=yes,width=800,height=900");if(!popup)throw new Error();popupRef.current=popup;setMessage("Review acceptance in DeSo Identity.")}catch{setMessage("Transfer acceptance could not be prepared. VIA changed nothing.");setBusy(false)}}
 if(!session||pending.length===0)return null
 return <section className="mt-5 rounded-xl border border-green-900/60 bg-black/25 p-4"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-green-500">Incoming NFT</p><h2 className="mt-2 text-lg font-semibold">Accept transfer</h2><p className="mt-2 text-sm text-zinc-400">DeSo marks these editions as pending for your active account. Ownership completes only after your signed acceptance.</p><label className="mt-3 flex items-start gap-2 text-xs text-amber-200"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I understand this accepts a real on-chain NFT transfer.</label><div className="mt-3 flex flex-wrap gap-2">{pending.map(e=><button key={e.serialNumber} disabled={!confirmed||busy} onClick={()=>void accept(e.serialNumber)} className="rounded-lg border border-green-700 px-4 py-2 text-sm font-semibold text-green-300 disabled:text-zinc-600">Accept edition #{e.serialNumber}</button>)}</div>{message?<p className="mt-3 text-xs text-zinc-400" role="status">{message}</p>:null}</section>
}
